#!/bin/bash

# Enable yabai
yabai -m signal --add event window_created_for_app --action "yabai -m window --focus last"
yabai -m signal --add event application_launched --action "yabai -m space --focus last; yabai -m window --focus last"

# Set default layout to bsp
yabai -m config layout bsp

# Set padding and gap
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

# Apps specifics
yabai -m rule --add app='System Settings' manage=off
yabai -m rule --add app='Calculator' manage=off
yabai -m rule --add app='Bitwarden' manage=off
# ----
# Regras para alternar layouts automaticamente
# ----

yabai -m signal --add event="window_created|window_destroyed" \
    action="NUM_WINDOWS=$(yabai -m query --windows --space | jq '. | length'); \
    if [ \"$NUM_WINDOWS\" -gt 1 ]; then \
        yabai -m space --layout bsp; \
    elif [ \"$NUM_WINDOWS\" -eq 1 ]; then \
        yabai -m space --layout float; \
        yabai -m window --toggle float; \
        yabai -m window --center; \
    fi"

